// One-off helper: converts the existing menu-data.js into supabase/seed.sql,
// so the current Ayeka Bar menu becomes the initial draft+published content
// for its row in the `menus` table. Run with: node scripts/generate-seed.js
"use strict";
const path = require("path");
const fs = require("fs");

const { MENU, BADGES } = require(path.join(__dirname, "..", "menu-data.js"));

const sqlString = (s) => "'" + JSON.stringify(s).replace(/'/g, "''") + "'";

const menuJson = { categories: MENU.categories };
const sql = `-- Generated by scripts/generate-seed.js from menu-data.js — review before running.
-- Replace OWNER_USER_ID below with the auth.users.id of the account that should
-- own this menu (create that user first: Authentication → Users → Add user).

insert into public.menus (slug, owner_id, name, badges, draft, published, published_at)
values (
  'ayeka-bar',
  'OWNER_USER_ID', -- TODO: paste the real auth.users.id here before running
  ${sqlString(MENU.name)}::jsonb,
  ${sqlString(BADGES)}::jsonb,
  ${sqlString(menuJson)}::jsonb,
  ${sqlString(menuJson)}::jsonb,
  now()
);
`;

fs.writeFileSync(path.join(__dirname, "..", "supabase", "seed.sql"), sql);
console.log("Wrote supabase/seed.sql — edit OWNER_USER_ID before running it in the Supabase SQL editor.");
